version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ai-cost-optimizer-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: ai-cost-optimizer
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - ai-cost-optimizer-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-cost-optimizer-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://appuser:apppass123@mongodb:27017/ai-cost-optimizer?authSource=ai-cost-optimizer
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    networks:
      - ai-cost-optimizer-network

  # Optional: Add Redis for caching/sessions
  redis:
    image: redis:7-alpine
    container_name: ai-cost-optimizer-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-cost-optimizer-network

volumes:
  mongodb_data:
  redis_data:

networks:
  ai-cost-optimizer-network:
    driver: bridge